version: '3.8'

services:
  service_analyzer:
    build: ./service_analyzer
    container_name: service_analyzer
    ports:
      - "8080:8080"
    restart: always

  service_visualizer:
    build: ./service_visualizer
    container_name: service_visualizer
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - service_analyzer
