user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log notice;
pid        /var/run/nginx.pid;

events {
    worker_connections  1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    server {
        listen 80;

        # Внутренний DNS-сервер Docker для динамического поиска контейнеров
        resolver 127.0.0.11 valid=5s;

        # Обработка запросов к Python-визуализатору
        location / {
            set $visualizer_backend "http://service_visualizer:8000";
            proxy_pass $visualizer_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Обработка запросов к C++ анализатору
        location /analyze {
            set $analyzer_backend "http://service_analyzer:8080";
            proxy_pass $analyzer_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
